config/routes.rb
require 'sidekiq/web'
require "good_job/engine"

Rails.application.routes.draw do
  resources :email_templates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

   mount Sidekiq::Web => '/sidekiq'
  
  resources :password_resets, only: [:new, :create]

  resources :users, only: [:new, :create] do
    collection do
      get :confirm_email
    end
  end


  #resources :masters do
  #  collection do
  #    get :excel_import_new
  #    post :import_excel
  #    get :export
  #    post :create_segment
  #  end
  #  get :index
  #end

  resources :chatbots, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :chatbot_steps, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :chatbot_button_replies, only: [:new, :create, :edit, :update, :destroy]
      resources :chatbot_multimedia_replies, only: [:new, :create, :edit, :update, :destroy]
      resources :chatbot_location_replies, only: [:new, :create, :edit, :update, :destroy]
    end
  end

#  resources :master_segments, only: [:index, :new, :create, :edit, :update, :destroy] do
#    resources :segments, only: [:index, :new, :edit, :update, :create, :destroy, :show]
#  end

  resources :whatsapp_accounts, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :templates, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :broadcasts, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      post :send_now
    end
    resources :broadcast_reports, only: [:index]
  end

  resources :conversations, only: [:index] do 
    collection do
      get :conversations_by_phone_number
      post :respond
    end
  end

  resources :email_broadcasts, only: [:new, :create]
  resources :email_settings

  root "sessions#new"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login/user', to: 'sessions#new', as: 'login_user'

  get 'password_resets/:token/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch 'password_resets/:token', to: 'password_resets#update', as: 'update_password_reset'
  get 'confirm_email', to: 'users#confirm_email'

  post '/webhook', to: 'webhook#receive'
  get '/webhook', to: 'webhook#verify'

  get '/segments/by_id', to: "segments#segments_by_id", as: "segments_by_id"

  mount GoodJob::Engine => '/good_job'


end

app/models/chatbot_step.rb
class ChatbotStep < ApplicationRecord
    belongs_to :chatbot
    belongs_to :previous_chatbot_step, class_name: "ChatbotStep", optional: true
    belongs_to :chatbot_button_reply, class_name: "ChatbotButtonReply", optional: true
    
    belongs_to :created_by, class_name: "User"
    belongs_to :edited_by, class_name: "User", optional: true
    belongs_to :deleted_by, class_name: "User", optional: true

    has_many :chatbot_button_replies
    has_many :chatbot_multimedia_replies
    has_many :chatbot_location_replies

    validates :header, length: { maximum: 60 }
    validates :description, presence: true, length: { maximum: 1024 }
    validates :footer, length: { maximum: 60 }
    validates :list_button_caption, length: { maximum: 20 }
    validate :previous_chatbot_step_belongs_to_same_chatbot

    before_save :strip_and_downcase_trigger_master_segment_name
    before_update :strip_and_downcase_trigger_master_segment_name


    def previous_chatbot_step_belongs_to_same_chatbot
        if previous_chatbot_step && previous_chatbot_step.chatbot != chatbot
            errors.add(:previous_chatbot_step_id, "must belong to the same chatbot")
        end
    end

    def strip_and_downcase_trigger_master_segment_name
        self.trigger_master_segment_name = self.trigger_master_segment_name.strip.downcase if self.trigger_master_segment_name.present?
    end
end

app/controllers/chatbot_steps_controller.rb
class ChatbotStepsController < ApplicationController
    before_action :set_chatbot
    before_action :set_chatbot_step, only: [:edit, :update, :destroy]
    before_action :authorize_super_admin, only: [:index, :new, :create, :edit, :update, :destroy]

    def index
    end

    def new
        @chatbot_step = ChatbotStep.new
        @chatbot_button_reply_id = params[:chatbot_button_reply_id]
        @previous_chatbot_step_id = params[:previous_chatbot_step_id]
    end

    def create
        @chatbot_step = @chatbot.chatbot_steps.build(chatbot_step_params)
        @chatbot_step.created_by = current_user
        @chatbot_step.previous_chatbot_step = ChatbotStep.find(params[:previous_chatbot_step_id]) if params[:previous_chatbot_step_id].present?
        @chatbot_step.chatbot_button_reply_id = ChatbotButtonReply.find(params[:chatbot_button_reply_id]).id if params[:chatbot_button_reply_id].present?


        get_leading_button_reply
=begin
        if !check_existing_and_save_end_chatbot_step_master_segment(chatbot_step_params[:end_chabot])
            update_leading_button_reply_to_trigger
        else
            if !params[:chatbot_button_reply_id]
                 redirect_to new_chatbot_chatbot_step_path(@chatbot, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), alert: "Chatbot step creation failed , master segment already exists"
                 return
            end
        end
=end

        if @chatbot_step.save
            redirect_to edit_chatbot_chatbot_step_path(@chatbot, @chatbot_step, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), notice: "Chatbot step created successfully"
        else
            redirect_to new_chatbot_chatbot_step_path(@chatbot, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), alert: "Chatbot step creation failed #{@chatbot_step.errors.full_messages.join(', ')}"
        end
    end

    def edit
        @chatbot_step = ChatbotStep.find(params[:id])
        @previous_chatbot_step_id = params[:previous_chatbot_step_id]
    end

    def update
        @chatbot_step = ChatbotStep.find(params[:id])

        if !check_trigger_master_segment_name_change(chatbot_step_params)
            redirect_to edit_chatbot_chatbot_step_path(@chatbot, @chatbot_step, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), alert: "You are not allowed to change the trigger master segment name"
            return;
        end
        get_leading_button_reply
=begin
        if !check_existing_and_save_end_chatbot_step_master_segment(chatbot_step_params[:end_chabot])
            update_leading_button_reply_to_trigger
        else
            if !params[:chatbot_button_reply_id]
                 redirect_to new_chatbot_chatbot_step_path(@chatbot, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), alert: "Chatbot step update failed , master segment already exists"
                 return
            end
        end
=end

        @chatbot_step.edited_by = current_user
        if @chatbot_step.update(chatbot_step_params)
            redirect_to edit_chatbot_chatbot_step_path(@chatbot, @chatbot_step, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), notice: "Chatbot step updated successfully"
        else
            redirect_to edit_chatbot_chatbot_step_path(@chatbot, @chatbot_step, previous_chatbot_step_id: @chatbot_step.previous_chatbot_step_id, chatbot_button_reply_id: @chatbot_step.chatbot_button_reply_id), alert: "Chatbot step update failed #{@chatbot_step.errors.full_messages.join(', ')}"
        end
    end

    def destroy
        @chatbot_step = ChatbotStep.find(params[:id])
        @chatbot_step.deleted_by = current_user
        @chatbot_step.is_deleted = true
        @chatbot_step.save
        redirect_to chatbots_path, notice: "Chatbot step deleted successfully"
    end

    private

    def set_chatbot
        @chatbot = Chatbot.find(params[:chatbot_id])
    end

    def set_chatbot_step
        @chatbot_step = @chatbot.chatbot_steps.find(params[:id])
    end

    def chatbot_step_params
        params.require(:chatbot_step).permit(:header, :description, :footer, :list_button_caption, :previous_chatbot_step_id, :chatbot_id, :chatbot_button_reply_id, :end_chabot, :end_chabot_reply, :has_go_back_to_main, :go_back_to_main_button_title, :trigger_master_segment_name)
    end

    def get_leading_button_reply
        if @chatbot_step.chatbot_button_reply_id.present?
            @chatbot_button_reply = ChatbotButtonReply.find(@chatbot_step.chatbot_button_reply_id);
        end
    end

    def update_leading_button_reply_to_trigger
        if @chatbot_step.trigger_master_segment_name.present?
            if @chatbot_button_reply.present? 
                @chatbot_button_reply.update(is_trigger: true, trigger_keyword: @chatbot_step.trigger_master_segment_name);
            end
        end
    end

    def check_existing_and_save_end_chatbot_step_master_segment(is_end_chatbot_step)
        if is_end_chatbot_step
            existing_msater_segment = MasterSegment.find_by(name: @chatbot_step.trigger_master_segment_name, is_deleted: false);
            if existing_msater_segment.present?
                return true;
            else
                chain_of_steps = @chatbot_button_reply.chain_of_steps
                @master_segment = MasterSegment.create(name: @chatbot_step.trigger_master_segment_name, chain_of_steps: chain_of_steps, added_by: current_user);
                return false;
            end
        end
        
    end

    def check_trigger_master_segment_name_change(chatbot_step_params)
        if chatbot_step_params[:end_chabot] == "1" 
            if @chatbot_step.trigger_master_segment_name != chatbot_step_params[:trigger_master_segment_name] && @chatbot_step.trigger_master_segment_name.present?
                return false;
            end
        end
        return true;
    end


end

app/views/chatbot_steps/_chatbot_button_reply_modal.html.erb
<!-- Reply Option Modal -->
<div class="modal fade" id="<%= reply_modal_id %>" tabindex="-1" aria-labelledby="replyOptionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="replyOptionModalLabel">Add Reply Option</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "chatbot_button_replies/form", chatbot_button_reply: ChatbotButtonReply.new %>
      </div>
    </div>
  </div>
</div>

app/views/chatbot_steps/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(
      url: @chatbot_step.id.present? ? chatbot_chatbot_step_path(@chatbot, @chatbot_step) : chatbot_chatbot_steps_path(@chatbot),
      method: @chatbot_step.id.present? ? :patch : :post, 
      local: true, 
      class: "needs-validation",
      model: @chatbot_step,
    ) do |f| %>
      <%= render "shared_partials/error", model: @chatbot_step %>
      
      <% if @chatbot_step.id.present? %>
        <%= render "shared_partials/error", model: @chatbot_step %>
      <% end %>

      <div class="mb-3">
        <%= f.label :header, class: "form-label" %> <span class="text-danger">Max 60 characters</span>
        <%= f.text_field :header, class: "form-control", required: true, maxlength: 60, value: @chatbot_step.header %>
      </div>

      <div class="mb-3">
        <%= f.label :description, class: "form-label" %> <span class="text-danger">Max 1024 characters</span>
        <%= f.text_area :description, class: "form-control", rows: 5, required: true, maxlength: 1024, value: @chatbot_step.description %>
      </div>

      <div class="mb-3">
        <%= f.label :footer, class: "form-label" %> <span class="text-danger">Max 60 characters</span>
        <%= f.text_field :footer, class: "form-control", maxlength: 60, value: @chatbot_step.footer %>
      </div>

      <div class="mb-3">
        <%= f.label :list_button_caption, class: "form-label" %> <span class="text-danger">Max 20 characters</span>
        <%= f.text_field :list_button_caption, class: "form-control", maxlength: 20, value: @chatbot_step.list_button_caption %>
      </div>

      <div class="mb-3">
        <%= f.check_box :end_chabot, class: "form-check-input", checked: @chatbot_step.end_chabot == true %>
        <%= f.label :end_chabot, class: "form-label" %>
      </div>

      <div class="mb-3 end-chatbot-fields" style="display: none;">
        <%= f.label :end_chabot_reply, class: "form-label" %>
        <%= f.text_field :end_chabot_reply, class: "form-control", value: @chatbot_step.end_chabot_reply %>
      </div>

      <div class="mb-3 end-chatbot-fields" style="display: none;">
        <%= f.check_box :has_go_back_to_main, class: "form-check-input", checked: @chatbot_step.has_go_back_to_main == true %>
        <%= f.label :has_go_back_to_main, class: "form-label" %>
      </div>

      <div class="mb-3 end-chatbot-fields" style="display: none;">
        <%= f.label :go_back_to_main_button_title, class: "form-label" %>
        <%= f.text_field :go_back_to_main_button_title, class: "form-control", value: @chatbot_step.go_back_to_main_button_title %>
      </div>

      <div class="mb-3 end-chatbot-fields" style="display: none;">
        <%= f.label :trigger_master_segment_name, class: "form-label" %>
        <%= f.text_field :trigger_master_segment_name, class: "form-control", value: @chatbot_step.trigger_master_segment_name %>
      </div>

      <% if @previous_chatbot_step_id.present? %>
        <%= f.hidden_field :previous_chatbot_step_id, value: @previous_chatbot_step_id %>
      <% end %>
      <% if @chatbot_button_reply_id.present? %>
        <%= f.hidden_field :chatbot_button_reply_id, value: @chatbot_button_reply_id %>
      <% end %>

      <%= f.submit class: "btn btn-primary my-3" %>

      <div class="mb-3">
        <% if request.path.include?('edit') %>
          <%= link_to "Add Reply Option", "#", class: "btn btn-info", data: { bs_toggle: "modal", bs_target: "#replyOptionModal" } %>
          <%= link_to "Add Multimedia Reply", "#", class: "btn btn-success", data: { bs_toggle: "modal", bs_target: "#multimediaReplyModal" } %>
          <%= link_to 'Add Location Reply', "#", class: "btn btn-warning", data: { bs_toggle: "modal", bs_target: "#locationReplyModal" } %>
          <%= link_to "Back", @previous_chatbot_step_id.present? ? edit_chatbot_chatbot_step_path(@chatbot, ChatbotStep.find(@previous_chatbot_step_id), params:{previous_chatbot_step_id: ChatbotStep.find(@previous_chatbot_step_id).previous_chatbot_step_id}) : chatbots_path, class: "btn btn-secondary" %>

          <!-- Button Reply Table -->
          <% if @chatbot_step.chatbot_button_replies.includes(:added_by).where(is_deleted: false).any? %>
            <div class="table-responsive mt-3">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Order</th>
                    <th>Action Type</th>
                    <th>Added By</th>
                    <th>Added On</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @chatbot_step.chatbot_button_replies.where(is_deleted: false).order(:order).each do |reply| %>
                    <tr>
                      <td><%= reply.title %></td>
                      <td><%= reply.order %></td>
                      <td><%= reply.action_type_id.to_s.humanize %></td>
                      <td><%= reply.added_by&.email %></td>
                      <td><%= reply.added_on&.strftime("%Y-%m-%d %H:%M") %></td>
                      <td>
                        <%= link_to "Edit", edit_chatbot_chatbot_step_chatbot_button_reply_path(@chatbot, @chatbot_step, reply),
                            class: "btn btn-sm btn-warning" %>
                        <%= link_to "Delete", chatbot_chatbot_step_chatbot_button_reply_path(@chatbot, @chatbot_step, reply), 
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                            class: "btn btn-sm btn-danger" %>
                        <%= link_to "Next Step", ChatbotStep.find_by(chatbot_button_reply_id: reply.id).present? ? edit_chatbot_chatbot_step_path(@chatbot, ChatbotStep.find_by(chatbot_button_reply_id: reply.id), params:{previous_chatbot_step_id: @chatbot_step.id}) : new_chatbot_chatbot_step_path(@chatbot, params: { chatbot_button_reply_id: reply.id, previous_chatbot_step_id: @chatbot_step.id }),
                            class: "btn btn-sm btn-success" %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- Button Reply Table  END-->

<!-- Multimedia Reply Table -->
<% if @chatbot_step.chatbot_multimedia_replies.where(is_deleted: false).any? %>
  <div class="table-responsive mt-3">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Media Type</th>
          <th>Order</th>
          <th>Text Body</th>
          <th>File Caption</th>
          <th>Added By</th>
          <th>Added On</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @chatbot_step.chatbot_multimedia_replies.includes(:added_by).where(is_deleted: false).order(:order).each do |reply| %>
          <tr>
            <td><%= reply.media_type_id.to_s.humanize %></td>
            <td><%= reply.order %></td>
            <td><%= reply.text_body %></td>
            <td><%= reply.file_caption %></td>
            <td><%= reply.added_by&.email %></td>
            <td><%= reply.added_on&.strftime("%Y-%m-%d %H:%M") %></td>
            <td>
              <%= link_to "Edit", edit_chatbot_chatbot_step_chatbot_multimedia_reply_path(@chatbot, @chatbot_step, reply),
                  class: "btn btn-sm btn-warning" %>
              <%= link_to "Delete", chatbot_chatbot_step_chatbot_multimedia_reply_path(@chatbot, @chatbot_step, reply),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: "btn btn-sm btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<!-- Multimedia Reply Table END-->

<!-- Location Reply Table -->
<% if @chatbot_step.chatbot_location_replies.includes(:added_by).where(is_deleted: false).any? %>
  <div class="table-responsive mt-3">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Location Name</th>
          <th>Address</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th>Order</th>
          <th>Added By</th>
          <th>Added On</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @chatbot_step.chatbot_location_replies.includes(:added_by).where(is_deleted: false).order(:order).each do |reply| %>
          <tr>
            <td><%= reply.location_name %></td>
            <td><%= reply.location_address %></td>
            <td><%= reply.location_latitude %></td>
            <td><%= reply.location_longitude %></td>
            <td><%= reply.order %></td>
            <td><%= reply.added_by&.email %></td>
            <td><%= reply.added_on&.strftime("%Y-%m-%d %H:%M") %></td>
            <td>
              <%= link_to "Edit", edit_chatbot_chatbot_step_chatbot_location_reply_path(@chatbot, @chatbot_step, reply),
                  class: "btn btn-sm btn-warning" %>
              <%= link_to "Delete", chatbot_chatbot_step_chatbot_location_reply_path(@chatbot, @chatbot_step, reply, params: {chatbot: @chatbot, chatbot_step: @chatbot_step}),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: "btn btn-sm btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<!-- Location Reply Table END-->    

<!-- Button Reply Modal -->
<% if @chatbot_step.id.present? %>
  <%= render "chatbot_button_reply_modal", reply_title: "", reply_order: "", reply_action_type: "", reply_modal_id: "replyOptionModal", endpoint: nil %>
<% end %>
<!-- Multimedia Reply Modal -->
<% if @chatbot_step.id.present? %>
  <div class="modal fade" id="multimediaReplyModal" tabindex="-1" aria-labelledby="multimediaReplyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="multimediaReplyModalLabel">Add Multimedia Reply</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render "chatbot_multimedia_replies/form", chatbot_multimedia_reply: ChatbotMultimediaReply.new %>
      </div>
    </div>
  </div>

<!-- Location Reply Modal -->
  <div class="modal fade" id="locationReplyModal" tabindex="-1" aria-labelledby="locationReplyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="locationReplyModalLabel">Add Location Reply</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render "chatbot_location_replies/form", chatbot_location_reply: ChatbotLocationReply.new %>
      </div>
    </div>
    </div>
<% end %>


<!-- Toggle End Chatbot Fields  in the chatbot step form-->
<script>
  function initializeEndChatbotFields() {
    const endChatbotCheckbox = document.querySelector('#chatbot_step_end_chabot');
    const endChatbotFields = document.querySelectorAll('.end-chatbot-fields');
    
    function toggleEndChatbotFields() {
      endChatbotFields.forEach(field => {
        field.style.display = endChatbotCheckbox.checked ? 'block' : 'none';
      });
    }

    endChatbotCheckbox.addEventListener('change', toggleEndChatbotFields);
    toggleEndChatbotFields(); // Initial state
  }

  // Run on both turbo:load and DOMContentLoaded to handle all cases
  document.addEventListener('turbo:load', initializeEndChatbotFields);
  document.addEventListener('DOMContentLoaded', initializeEndChatbotFields);
</script>

app/views/chatbot_steps/edit.hml.erb
<%= render "form", chatbot_step: @chatbot_step %>

app/views/chatbot_steps/edit.html.erb
<%= render "form", chatbot_step: @chatbot_step %>

app/views/chatbot_steps/new.html.erb
<%= render "form", chatbot_step: @chatbot_step %>
    